### ISSUE TITLE
`maxLineLengthHeader` feature

### ISSUE THREAD

**Issue by allanbowe** [sasjs/lint#45]
Comments can contain long urls, also table markdown, that cannot be shortened

We should provide an automatic exception for these in the line length limit.

![image](https://user-images.githubusercontent.com/4420615/117161918-ff1cab00-adca-11eb-8402-75ab568fbc3c.png)

**Comment by sasutils** [comment]
Might be better to have the ability to specify a separate limit rather than totally ignore long lines in comment blocks.  

Or perhaps something that can detect when it is a single long "word" that is exceeding the line limit.  That would handle the example of the long URL in the comment block.

**Comment by allanbowe** [comment]
@sasutils - I like your idea of ignoring a "word" (ie, string without a space)!  Thanks for the suggestion!

**Comment by allanbowe** [comment]
On retrospect, the single word idea won't work as we also need it to work for table markdown (where each row must be on one line, and can contain spaces)

So your first idea is on the table.  A new config option `maxLineLengthHeader` (to work only with the header section) that will default to `max(maxLineLengthHeader,maxLineLength)`

**Comment by sabhas** [comment]
via Hubstaff
User: Sabir Hassan

Project: SASjs lint - https://app.hubstaff.com/projects/2310878
Date Range: 01/09/23 - 01/10/23
Work session total: 9:19:59
Billable: Yes

Grand total: 9:19:59
