### ISSUE TITLE
macroNameinMend option incorrectly adds macro system option to the %mend statement

### ISSUE THREAD

**Issue by rafgag** [sasjs/lint#53]
If SAS macro name contains any macro system options (e.g. /minoperator), then these options are added to the %mend statement, when `macroNameinMend` is set to 'true' in the `.sasjslint` file and '**Format Document**' option (in the right-click menu) is selected.

Example:

![image](https://user-images.githubusercontent.com/69139928/118942653-38205800-b953-11eb-8773-427be4c07023.png)

Result: A warning message in the SAS log during the execution.

![image](https://user-images.githubusercontent.com/69139928/118942768-525a3600-b953-11eb-85a7-40db0c9bceb4.png)

**Comment by allanbowe** [comment]
Indeed - the end of the `%macro statement` can contain a set of options, delimted by a `/`.  There are examples at the bottom of the [documentation](https://documentation.sas.com/doc/en/pgmsascdc/9.4_3.5/mcrolref/p1nypovnwon4uyn159rst8pgzqrl.htm).  We will fix.

**Comment by saadjutt01** [comment]
`%mend` syntax remains the same,
`%macro` syntax needs to be updated for parameter-list and available options:

Syntax: `%MACRO macro-name <(parameter-list)> </ options>;`
